import {
    Head,
    router,
} from '@inertiajs/react';

import CMSLayout from '@/layouts/CMSLayout';

interface NotificationData {
    action?: string;
    severity?: string;

    entity_type?: string;
    entity_name?: string | null;
    entity_id?: number;

    deletion_batch_id?: number;

    performed_by_name?: string;

    title?: string;
    message?: string;

    occurred_at?: string;
}

interface CmsNotification {
    id: string;
    type: string;

    data: NotificationData;

    read_at: string | null;
    created_at: string;
}

interface PaginationLink {
    url: string | null;
    label: string;
    active: boolean;
}

interface PaginatedNotifications {
    data: CmsNotification[];

    current_page: number;
    last_page: number;

    from: number | null;
    to: number | null;
    total: number;

    links: PaginationLink[];
}

interface NotificationIndexProps {
    notifications: PaginatedNotifications;
    unreadCount: number;
}

export default function Index({
    notifications,
    unreadCount,
}: NotificationIndexProps) {

    const formatDate = (
        value?: string
    ): string => {
        if (! value) {
            return '-';
        }

        const date =
            new Date(
                value.replace(
                    ' ',
                    'T'
                )
            );

        if (
            Number.isNaN(
                date.getTime()
            )
        ) {
            return value;
        }

        return date.toLocaleString();
    };


    const markAsRead = (
        notification: CmsNotification
    ) => {
        if (
            notification.read_at
        ) {
            return;
        }

        router.post(
            `/admin/notifications/${notification.id}/read`,
            {},
            {
                preserveScroll:
                    true,
            }
        );
    };


    const markAllAsRead =
        () => {
            if (
                unreadCount ===
                0
            ) {
                return;
            }

            router.post(
                '/admin/notifications/read-all',
                {},
                {
                    preserveScroll:
                        true,
                }
            );
        };


    const getSeverityClass = (
        severity?: string
    ): string => {
        if (
            severity ===
            'critical'
        ) {
            return `
                bg-red-50
                text-red-700
                border-red-200
            `;
        }

        if (
            severity ===
            'warning'
        ) {
            return `
                bg-amber-50
                text-amber-700
                border-amber-200
            `;
        }

        return `
            bg-blue-50
            text-blue-700
            border-blue-200
        `;
    };


    return (
        <CMSLayout>

            <Head
                title="Notifications"
            />


            <div
                className="
                    space-y-6
                "
            >

                <div
                    className="
                        flex
                        flex-wrap
                        items-end
                        justify-between
                        gap-4
                    "
                >

                    <div>

                        <p
                            className="
                                text-xs
                                font-bold
                                uppercase
                                tracking-[0.16em]
                                text-[#0A5F9E]
                            "
                        >
                            CMS Administration
                        </p>


                        <h1
                            className="
                                mt-2
                                text-2xl
                                font-semibold
                                text-gray-900
                            "
                        >
                            Notifications
                        </h1>


                        <p
                            className="
                                mt-1
                                max-w-2xl
                                text-sm
                                leading-6
                                text-gray-600
                            "
                        >
                            Review deletion, restoration and permanent-deletion
                            alerts generated by the CMS.
                        </p>

                    </div>


                    <div
                        className="
                            flex
                            items-center
                            gap-3
                        "
                    >

                        <div
                            className="
                                rounded-xl
                                border
                                border-gray-200
                                bg-white
                                px-5
                                py-3
                                shadow-sm
                            "
                        >

                            <p
                                className="
                                    text-xs
                                    font-medium
                                    text-gray-500
                                "
                            >
                                Unread
                            </p>

                            <p
                                className="
                                    mt-1
                                    text-xl
                                    font-semibold
                                    text-gray-900
                                "
                            >
                                {unreadCount}
                            </p>

                        </div>


                        {unreadCount >
                            0 && (

                            <button
                                type="button"
                                onClick={
                                    markAllAsRead
                                }
                                className="
                                    rounded-lg
                                    bg-[#0A5F9E]
                                    px-4
                                    py-2.5
                                    text-sm
                                    font-semibold
                                    text-white
                                    transition
                                    hover:bg-[#084d80]
                                "
                            >
                                Mark all as read
                            </button>

                        )}

                    </div>

                </div>


                <div
                    className="
                        overflow-hidden
                        rounded-xl
                        border
                        border-gray-200
                        bg-white
                        shadow-sm
                    "
                >

                    {notifications.data.length >
                    0 ? (

                        <div
                            className="
                                divide-y
                                divide-gray-100
                            "
                        >

                            {notifications.data.map(
                                (
                                    notification
                                ) => {

                                    const isUnread =
                                        !notification.read_at;

                                    const severity =
                                        notification
                                            .data
                                            .severity ??
                                        'info';

                                    return (

                                        <div
                                            key={
                                                notification.id
                                            }
                                            className={`
                                                p-5
                                                transition

                                                ${
                                                    isUnread
                                                        ? 'bg-blue-50/30'
                                                        : 'bg-white'
                                                }
                                            `}
                                        >

                                            <div
                                                className="
                                                    flex
                                                    flex-col
                                                    gap-4
                                                    lg:flex-row
                                                    lg:items-start
                                                    lg:justify-between
                                                "
                                            >

                                                <div
                                                    className="
                                                        min-w-0
                                                        flex-1
                                                    "
                                                >

                                                    <div
                                                        className="
                                                            flex
                                                            flex-wrap
                                                            items-center
                                                            gap-2
                                                        "
                                                    >

                                                        <span
                                                            className={`
                                                                inline-flex
                                                                rounded-full
                                                                border
                                                                px-2.5
                                                                py-1
                                                                text-xs
                                                                font-semibold
                                                                uppercase

                                                                ${getSeverityClass(
                                                                    severity
                                                                )}
                                                            `}
                                                        >
                                                            {severity}
                                                        </span>


                                                        {isUnread && (

                                                            <span
                                                                className="
                                                                    inline-flex
                                                                    rounded-full
                                                                    bg-red-50
                                                                    px-2.5
                                                                    py-1
                                                                    text-xs
                                                                    font-semibold
                                                                    text-red-700
                                                                "
                                                            >
                                                                Unread
                                                            </span>

                                                        )}

                                                    </div>


                                                    <h2
                                                        className="
                                                            mt-3
                                                            text-base
                                                            font-semibold
                                                            text-gray-900
                                                        "
                                                    >
                                                        {notification
                                                            .data
                                                            .title ??
                                                            'CMS Activity'}
                                                    </h2>


                                                    <p
                                                        className="
                                                            mt-1
                                                            text-sm
                                                            leading-6
                                                            text-gray-600
                                                        "
                                                    >
                                                        {notification
                                                            .data
                                                            .message ??
                                                            'CMS notification'}
                                                    </p>


                                                    <div
                                                        className="
                                                            mt-3
                                                            flex
                                                            flex-wrap
                                                            gap-x-4
                                                            gap-y-1
                                                            text-xs
                                                            text-gray-500
                                                        "
                                                    >

                                                        <span>
                                                            {formatDate(
                                                                notification
                                                                    .data
                                                                    .occurred_at ??
                                                                    notification
                                                                        .created_at
                                                            )}
                                                        </span>


                                                        {notification
                                                            .data
                                                            .performed_by_name && (

                                                            <span>
                                                                By:{' '}
                                                                {
                                                                    notification
                                                                        .data
                                                                        .performed_by_name
                                                                }
                                                            </span>

                                                        )}


                                                        {notification
                                                            .data
                                                            .deletion_batch_id && (

                                                            <span>
                                                                Batch #
                                                                {
                                                                    notification
                                                                        .data
                                                                        .deletion_batch_id
                                                                }
                                                            </span>

                                                        )}

                                                    </div>

                                                </div>


                                                <div
                                                    className="
                                                        flex
                                                        shrink-0
                                                        items-center
                                                        gap-2
                                                    "
                                                >

                                                    {isUnread && (

                                                        <button
                                                            type="button"
                                                            onClick={() =>
                                                                markAsRead(
                                                                    notification
                                                                )
                                                            }
                                                            className="
                                                                rounded-lg
                                                                border
                                                                border-gray-300
                                                                bg-white
                                                                px-4
                                                                py-2
                                                                text-sm
                                                                font-semibold
                                                                text-gray-700
                                                                transition
                                                                hover:bg-gray-50
                                                            "
                                                        >
                                                            Mark as read
                                                        </button>

                                                    )}

                                                </div>

                                            </div>

                                        </div>

                                    );
                                }
                            )}

                        </div>

                    ) : (

                        <div
                            className="
                                px-6
                                py-16
                                text-center
                            "
                        >

                            <div
                                className="
                                    mx-auto
                                    flex
                                    h-12
                                    w-12
                                    items-center
                                    justify-center
                                    rounded-full
                                    bg-gray-100
                                    text-xl
                                "
                            >
                                ✓
                            </div>


                            <h3
                                className="
                                    mt-4
                                    text-base
                                    font-semibold
                                    text-gray-900
                                "
                            >
                                No notifications
                            </h3>


                            <p
                                className="
                                    mx-auto
                                    mt-2
                                    max-w-md
                                    text-sm
                                    leading-6
                                    text-gray-500
                                "
                            >
                                CMS deletion, restoration and permanent-delete
                                alerts will appear here.
                            </p>

                        </div>

                    )}

                </div>


                {notifications.last_page >
                    1 && (

                    <div
                        className="
                            flex
                            flex-wrap
                            items-center
                            justify-between
                            gap-3
                        "
                    >

                        <p
                            className="
                                text-sm
                                text-gray-500
                            "
                        >
                            Showing{' '}
                            {notifications.from ??
                                0}
                            {' '}to{' '}
                            {notifications.to ??
                                0}
                            {' '}of{' '}
                            {notifications.total}
                        </p>


                        <div
                            className="
                                flex
                                flex-wrap
                                gap-2
                            "
                        >

                            {notifications.links.map(
                                (
                                    link,
                                    index
                                ) => (

                                    <button
                                        key={
                                            `${link.label}-${index}`
                                        }
                                        type="button"
                                        disabled={
                                            !link.url
                                        }
                                        onClick={() => {
                                            if (
                                                !link.url
                                            ) {
                                                return;
                                            }

                                            router.visit(
                                                link.url,
                                                {
                                                    preserveScroll:
                                                        true,
                                                }
                                            );
                                        }}
                                        className={`
                                            rounded-lg
                                            border
                                            px-3
                                            py-2
                                            text-sm
                                            transition

                                            ${
                                                link.active
                                                    ? 'border-[#0A5F9E] bg-[#0A5F9E] text-white'
                                                    : 'border-gray-300 bg-white text-gray-700 hover:bg-gray-50'
                                            }

                                            disabled:cursor-not-allowed
                                            disabled:opacity-40
                                        `}
                                        dangerouslySetInnerHTML={{
                                            __html:
                                                link.label,
                                        }}
                                    />

                                )
                            )}

                        </div>

                    </div>

                )}

            </div>

        </CMSLayout>
    );
}
