<?php

namespace App\Http\Controllers;

use App\Models\JobApplication;
use App\Models\JobOpening;
use App\Models\Language;
use App\Models\Website;
use App\Services\TranslationService;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Validation\Rule;
use Inertia\Inertia;

class CareerController extends Controller
{
    /**
     * Dynamic JobOpening fields that visitors should see
     * in their selected public website language.
     */
    private const TRANSLATABLE_JOB_FIELDS = [
        'title',
        'department',
        'location',
        'employment_type',
        'experience',
        'short_description',
        'description',
        'responsibilities',
        'requirements',
        'qualifications',
    ];

    /**
     * Careers listing UI text.
     *
     * These are English source strings only.
     * They are NOT per-language hardcoded translations.
     * TranslationService translates/cache them for any active CMS language.
     */
    private const CAREERS_UI = [
        'page_title' => 'Careers',

        'eyebrow' => 'Career Opportunities',

        'heading' => 'Current Openings',

        'intro' => 'Browse our available career opportunities and find the position that matches your skills, experience and career goals.',

        'no_openings' => 'No Current Openings',

        'no_openings_description' => 'There are currently no available job openings. Please check again later for new opportunities.',

        'open' => 'Open',

        'experience' => 'Experience',

        'closing_date' => 'Application Closing Date',

        'view_details' => 'View Job Details',
    ];

    /**
     * Job details page UI text.
     *
     * Again, only one English source exists.
     * Other languages are generated by TranslationService and cached.
     */
    private const JOB_DETAILS_UI = [
        'back_to_careers' => 'Back to Careers',

        'career_opportunity' => 'Career Opportunity',

        'department' => 'Department',

        'location' => 'Location',

        'experience' => 'Experience',

        'job_description' => 'Job Description',

        'responsibilities' => 'Responsibilities',

        'requirements' => 'Requirements',

        'qualifications' => 'Qualifications',

        'apply_now' => 'Apply Now',

        'interested' => 'Interested in this role?',

        'apply_description' => 'Submit your application and our recruitment team will review your profile.',

        'closing_date' => 'Application Closing Date',
    ];

    public function __construct(
        private readonly TranslationService $translationService
    ) {}

    /**
     * Display all active job openings.
     */
    public function index(Request $request)
    {
        $website = $this->resolveCurrentWebsite($request);

        $jobs = JobOpening::query()
            ->whereHas(
                'websites',
                function ($query) use ($website) {
                    $query->where(
                        'websites.id',
                        $website->id
                    );
                }
            )
            ->where('status', 'active')
            ->where(function ($query) {
                $query
                    ->whereNull('closing_date')
                    ->orWhereDate(
                        'closing_date',
                        '>=',
                        now()->toDateString()
                    );
            })
            ->latest()
            ->get();

        $languageCode = $this->resolveCurrentLanguage($request);

        return Inertia::render(
            'public/Careers',
            [
                'jobs' => $this->translateJobs(
                    jobs: $jobs,
                    targetLanguage: $languageCode
                ),
                'ui' => $this->translateUi(
                    source: self::CAREERS_UI,
                    targetLanguage: $languageCode,
                    context: 'public_careers_ui'
                ),
                'currentLanguage' => $languageCode,
                'currentWebsite' => [
                    'id' => $website->id,
                    'name' => $website->name,
                    'slug' => $website->slug,
                    'url' => $website->url,
                ],
            ]
        );
    }

    /**
     * Display a single job opening.
     */
    public function show(
        Request $request,
        string $slug
    ) {
        $website = $this->resolveCurrentWebsite($request);

        $job = $this->getAvailableJob(
            slug: $slug,
            website: $website
        );

        $languageCode = $this->resolveCurrentLanguage($request);

        return Inertia::render(
            'public/JobDetails',
            [
                'job' => $this->translateJob(
                    job: $job,
                    targetLanguage: $languageCode
                ),
                'ui' => $this->translateUi(
                    source: self::JOB_DETAILS_UI,
                    targetLanguage: $languageCode,
                    context: 'public_job_details_ui'
                ),
                'currentLanguage' => $languageCode,
                'currentWebsite' => [
                    'id' => $website->id,
                    'name' => $website->name,
                    'slug' => $website->slug,
                    'url' => $website->url,
                ],
            ]
        );
    }

    /**
     * Display the application form.
     *
     * The job information is translated.
     * The form fields/labels/options remain English intentionally.
     */
    public function apply(
        Request $request,
        string $slug
    ) {
        $website = $this->resolveCurrentWebsite($request);

        $job = $this->getAvailableJob(
            slug: $slug,
            website: $website
        );

        $languageCode = $this->resolveCurrentLanguage($request);

        return Inertia::render(
            'public/JobApply',
            [
                'job' => $this->translateJob(
                    job: $job,
                    targetLanguage: $languageCode
                ),
                'currentLanguage' => $languageCode,
                'currentWebsite' => [
                    'id' => $website->id,
                    'name' => $website->name,
                    'slug' => $website->slug,
                    'url' => $website->url,
                ],
            ]
        );
    }

    /**
     * Store a job application.
     *
     * Candidate-entered information is never translated.
     */
    public function storeApplication(
        Request $request,
        string $slug
    ) {
        $website = $this->resolveCurrentWebsite($request);

        $job = $this->getAvailableJob(
            slug: $slug,
            website: $website
        );

        $validated =
            $request->validate([

                /*
                |--------------------------------------------------------------------------
                | Personal Information
                |--------------------------------------------------------------------------
                */

                'name' => [
                    'required',
                    'string',
                    'max:255',
                ],

                'email' => [
                    'required',
                    'email',
                    'max:255',
                ],

                'phone' => [
                    'required',
                    'string',
                    'max:50',
                ],

                'current_location' => [
                    'required',
                    'string',
                    'max:255',
                ],

                /*
                |--------------------------------------------------------------------------
                | Work Authorization
                |--------------------------------------------------------------------------
                */

                'work_authorization' => [
                    'required',

                    Rule::in([
                        'Singapore Citizen',
                        'Singapore PR',
                        'EP Holder',
                        'S Pass Holder',
                        'Dependant Pass (DP) with Work Eligibility',
                        'Indian Citizen working in India',
                        'Other',
                    ]),
                ],

                'work_authorization_other' => [
                    Rule::requiredIf(
                        $request
                            ->work_authorization
                            === 'Other'
                    ),
                    'nullable',
                    'string',
                    'max:255',
                ],

                /*
                |--------------------------------------------------------------------------
                | Professional Information
                |--------------------------------------------------------------------------
                */

                'highest_qualification' => [
                    'required',
                    'string',
                    'max:255',
                ],

                'current_salary' => [
                    'nullable',
                    'string',
                    'max:100',
                ],

                'expected_salary' => [
                    'nullable',
                    'string',
                    'max:100',
                ],

                'notice_period' => [
                    'required',
                    'string',
                    'max:100',
                ],

                'shift_willingness' => [
                    'required',
                    'string',

                    Rule::in([
                        'Day shift',
                        'Night shift',
                        'Rotational shift',
                    ]),
                ],

                /*
                |--------------------------------------------------------------------------
                | Skills / Experience
                |--------------------------------------------------------------------------
                */

                'skills_project' => [
                    'required',
                    'string',
                    'max:5000',
                ],

                'experience_responsibilities' => [
                    'required',
                    'string',
                    'max:5000',
                ],

                /*
                |--------------------------------------------------------------------------
                | Resume
                |--------------------------------------------------------------------------
                */

                'resume' => [
                    'required',
                    'file',
                    'mimes:pdf,doc,docx',
                    'max:5120',
                ],

                /*
                |--------------------------------------------------------------------------
                | Cover Letter
                |--------------------------------------------------------------------------
                */

                'cover_letter' => [
                    'nullable',
                    'string',
                    'max:10000',
                ],
            ]);

        $resumePath =
            $request
                ->file('resume')
                ->store(
                    'job-applications/resumes',
                    'public'
                );

        JobApplication::create([
            'job_opening_id' => $job->id,

            /*
            |--------------------------------------------------------------------------
            | Source Website
            |--------------------------------------------------------------------------
            |
            | The current website has already been resolved from the incoming
            | hostname at the beginning of this method. Store that website ID
            | with the application so the centralized CMS can show exactly
            | which website/country the candidate applied from.
            |
            */

            'website_id' => $website->id,

            'name' => $validated['name'],

            'email' => $validated['email'],

            'phone' => $validated['phone'],

            'current_location' => $validated[
                    'current_location'
                ],

            'work_authorization' => $validated[
                    'work_authorization'
                ],

            'work_authorization_other' => $validated[
                    'work_authorization_other'
                ] ?? null,

            'highest_qualification' => $validated[
                    'highest_qualification'
                ],

            'current_salary' => $validated[
                    'current_salary'
                ] ?? null,

            'expected_salary' => $validated[
                    'expected_salary'
                ] ?? null,

            'notice_period' => $validated[
                    'notice_period'
                ],

            'shift_willingness' => $validated[
                    'shift_willingness'
                ],

            'skills_project' => $validated[
                    'skills_project'
                ],

            'experience_responsibilities' => $validated[
                    'experience_responsibilities'
                ],

            'resume' => $resumePath,

            'cover_letter' => $validated[
                    'cover_letter'
                ] ?? null,

            'status' => 'new',
        ]);

        return redirect()
            ->route(
                'careers.show',
                $job->slug
            )
            ->with(
                'success',
                'Your application has been submitted successfully.'
            );
    }

    /**
     * Translate page-level UI source strings.
     *
     * No language-specific dictionary exists in React/PHP.
     * TranslationService handles every currently active or future CMS language.
     */
    private function translateUi(
        array $source,
        string $targetLanguage,
        string $context
    ): array {
        if (
            $targetLanguage === '' ||
            $targetLanguage === 'en'
        ) {
            return $source;
        }

        return $this->translationService
            ->translateMany(
                texts: $source,
                targetLanguage: $targetLanguage,
                sourceLanguage: 'en',
                context: $context,
                recordId: null
            );
    }

    /**
     * Translate all jobs in the listing in one batch.
     */
    private function translateJobs(
        Collection $jobs,
        string $targetLanguage
    ): array {
        if (
            $targetLanguage === '' ||
            $targetLanguage === 'en'
        ) {
            return $jobs
                ->map(
                    fn (JobOpening $job) => $job->toArray()
                )
                ->values()
                ->all();
        }

        $texts = [];

        foreach ($jobs as $job) {
            foreach (
                self::TRANSLATABLE_JOB_FIELDS as $field
            ) {
                $value =
                    $job->{$field}
                    ?? null;

                if (
                    is_string($value) &&
                    trim($value) !== ''
                ) {
                    $texts[
                        "job.{$job->id}.{$field}"
                    ] = trim($value);
                }
            }
        }

        if ($texts === []) {
            return $jobs
                ->map(
                    fn (JobOpening $job) => $job->toArray()
                )
                ->values()
                ->all();
        }

        $translated =
            $this->translationService
                ->translateMany(
                    texts: $texts,
                    targetLanguage: $targetLanguage,
                    sourceLanguage: 'en',
                    context: 'public_careers',
                    recordId: null
                );

        return $jobs
            ->map(function (
                JobOpening $job
            ) use ($translated) {
                $jobData =
                    $job->toArray();

                foreach (
                    self::TRANSLATABLE_JOB_FIELDS as $field
                ) {
                    $key =
                        "job.{$job->id}.{$field}";

                    if (
                        array_key_exists(
                            $key,
                            $translated
                        ) &&
                        is_string(
                            $translated[$key]
                        )
                    ) {
                        $jobData[$field] =
                            $translated[$key];
                    }
                }

                return $jobData;
            })
            ->values()
            ->all();
    }

    /**
     * Translate one job.
     */
    private function translateJob(
        JobOpening $job,
        string $targetLanguage
    ): array {
        $jobData =
            $job->toArray();

        if (
            $targetLanguage === '' ||
            $targetLanguage === 'en'
        ) {
            return $jobData;
        }

        $texts = [];

        foreach (
            self::TRANSLATABLE_JOB_FIELDS as $field
        ) {
            $value =
                $job->{$field}
                ?? null;

            if (
                is_string($value) &&
                trim($value) !== ''
            ) {
                $texts[$field] =
                    trim($value);
            }
        }

        if ($texts === []) {
            return $jobData;
        }

        $translated =
            $this->translationService
                ->translateMany(
                    texts: $texts,
                    targetLanguage: $targetLanguage,
                    sourceLanguage: 'en',
                    context: 'public_career_job',
                    recordId: $job->id
                );

        foreach (
            self::TRANSLATABLE_JOB_FIELDS as $field
        ) {
            if (
                array_key_exists(
                    $field,
                    $translated
                ) &&
                is_string(
                    $translated[$field]
                )
            ) {
                $jobData[$field] =
                    $translated[$field];
            }
        }

        return $jobData;
    }

    /**
     * Resolve the active website from the incoming public hostname.
     */
    private function resolveCurrentWebsite(
        Request $request
    ): Website {
        $requestHost = strtolower(trim($request->getHost()));
        $requestPort = $request->getPort();

        $website = Website::query()
            ->where('status', 'active')
            ->get()
            ->first(function (Website $website) use ($requestHost, $requestPort) {
                $websiteUrl = trim((string) ($website->url ?? ''));

                if ($websiteUrl === '') {
                    return false;
                }

                $websiteHost = parse_url($websiteUrl, PHP_URL_HOST);

                if (! is_string($websiteHost)) {
                    return false;
                }

                if (strtolower(trim($websiteHost)) !== $requestHost) {
                    return false;
                }

                $websitePort = parse_url($websiteUrl, PHP_URL_PORT);

                if (
                    $websitePort !== null &&
                    (int) $websitePort !== (int) $requestPort
                ) {
                    return false;
                }

                return true;
            });

        abort_if(
            ! $website,
            404,
            'No active website is configured for this hostname.'
        );

        return $website;
    }

    /**
     * Resolve visitor language.
     */
    private function resolveCurrentLanguage(
        Request $request
    ): string {
        $preferredLanguage =
            strtolower(
                trim(
                    (string)
                    $request->cookie(
                        'preferred_language',
                        ''
                    )
                )
            );

        if (
            $preferredLanguage !== ''
        ) {
            $exists =
                Language::query()
                    ->where(
                        'code',
                        $preferredLanguage
                    )
                    ->where(
                        'status',
                        'active'
                    )
                    ->exists();

            if ($exists) {
                return $preferredLanguage;
            }
        }

        return Language::query()
            ->where(
                'is_default',
                true
            )
            ->where(
                'status',
                'active'
            )
            ->value('code')
            ?? 'en';
    }

    /**
     * Get an active and non-expired job.
     */
    private function getAvailableJob(
        string $slug,
        Website $website
    ): JobOpening {
        return JobOpening::query()
            ->whereHas(
                'websites',
                function ($query) use ($website) {
                    $query->where(
                        'websites.id',
                        $website->id
                    );
                }
            )
            ->where(
                'slug',
                $slug
            )
            ->where(
                'status',
                'active'
            )
            ->where(function ($query) {
                $query
                    ->whereNull(
                        'closing_date'
                    )
                    ->orWhereDate(
                        'closing_date',
                        '>=',
                        now()->toDateString()
                    );
            })
            ->firstOrFail();
    }
}
 